AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
